# Generated by Django 3.2.13 on 2022-05-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente_pf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=40, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('chave_ecac', models.CharField(max_length=14, unique=True)),
                ('senha_ecac', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=40)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
