# Generated by Django 3.2.13 on 2022-05-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pf', '0003_alter_clientepfmodel_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepfmodel',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
